name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/Obesity Classification Preprocessing.csv"
  TARGET_VAR: "Label"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow  
          
      # ✅ Step: Jalankan MLflow project
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      # ✅ Step: Ambil run_id dari model terakhir
      - name: Get latest MLflow run_id with model
        id: get_run
        run: |
          MODEL_PATH=$(find mlruns/0 -type d -path "*/artifacts/model" | head -n 1)
          if [ -z "$MODEL_PATH" ]; then
            echo "No model found!"
            exit 1
          fi
          RUN_ID=$(echo "$MODEL_PATH" | cut -d'/' -f3)
          echo "run_id=$RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # ✅ Step: Build Docker Model menggunakan run_id dari langkah sebelumnya
      - name: Build Docker Model
        run: |
          echo "Using run ID: ${{ steps.get_run.outputs.run_id }}"
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run.outputs.run_id }}/model" --name "cc"



      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_USERNAME }}/cc:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cc:latest